name: Continuous Integration - Develop Environment
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: deploy
        ports:
          - 3306:3306
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/deployment
        ports:
          - 7687:7687

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
        
      - name: Build and test
        run: ./gradlew test